export const GET_TEMPLATES_REQUEST = "GET_TEMPLATES_REQUEST";
export const GET_TEMPLATES_FULFILLED = "GET_TEMPLATES_FULFILLED";
export const GET_TEMPLATES_ERROR = "GET_TEMPLATES_ERROR";
export const FILTER_TEMPLATES_BY_CATEGORY = "FILTER_TEMPLATES_BY_CATEGORY";
export const FILTER_TEMPLATES_BY_ORDER = "FILTER_TEMPLATES_BY_ORDER";
export const FILTER_TEMPLATES_BY_DATE = "FILTER_TEMPLATES_BY_ORDER";
export const SEARCH_TEMPLATES_BY_CATEGORIES = "SEARCH_TEMPLATES_BY_CATEGORIES";